name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  portal-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build portal image
        run: docker build -f docker/portal.Dockerfile -t tavle-app-portal .

      - name: Build tavle image
        run: docker build -f docker/tavle.Dockerfile -t tavle-app-tavle .
